@startuml
!theme plain
skinparam componentStyle rectangle
skinparam packageStyle rectangle
skinparam DefaultFontName Arial

title Arquitectura del Sistema de Credenciales Digitales 

package "Capa de Presentación" as Frontend #F0F4F8 {
    component "Plugin Moodle\n(PHP)" as Moodle #FFFFFF
    component "Portal Alumno y Verificación\n(React / Vite)" as Portal #FFFFFF
}

package "Capa de Lógica de Negocio" as Backend #FFF9E6{
    component "API REST Central\n(Python / FastAPI)" as API #FFFFFF
    database "Base de Datos\n(Off-chain / Relacional)" as BD #FFFFFF
    component "Agente SSI\n(Aries Cloud Agent - Python)" as Agente #FFFFFF
}

package "Servicios Externos" as Externos #E8F5E9{
    component "Billetera Digital Estándar\n(App Móvil)" as Wallet #FFFFFF
}

package "Capa Blockchain" as Blockchain #E6F0FF {
    component "Red Hyperledger Besu\n(Ledger)" as Besu#FFFFFF
    
    note right of Besu
      Almacena DIDs públicos,
      Esquemas y Definiciones
      de Credenciales.
    end note
}

' Relaciones Frontend - Backend
Moodle -down-> API : 1. Solicita Emisión\n(HTTP/REST)
Portal -down-> API : 2. Autenticación y Gestión\n(HTTP/REST con JWT)

' Relaciones Internas Backend
API <-right-> BD : 3. Lectura/Escritura\n(ORM)
API <-down-> Agente : 4. Orquesta Emisión\n(Admin API)

' Relaciones SSI / Blockchain
Wallet <-right-> Agente : 5. Conexión y Transferencia\n(Protocolo DIDComm)
Agente <-down-> Besu: 6. Lectura/Escritura\nde Registros Públicos

@enduml